export const demoSentence =
  "The boy who won the prize is my brother, a quiet student reading by the window.";

export const demoAnnotations = [
  {
    id: "subject-main",
    start: 0,
    end: 7,
    role: "subject",
    fontLevel: 1,
    underlineStyle: "none",
    backgroundStyle: "none",
    labelZh: "主句主语",
    explanationZh: "The boy 作主句主语，后面的定语从句修饰 boy。",
  },
  {
    id: "head-boy",
    start: 4,
    end: 7,
    role: "subject",
    fontLevel: 1,
    underlineStyle: "none",
    backgroundStyle: "meaningCenter",
    labelZh: "意群中心词",
    explanationZh: "boy 是主语 The boy 的中心词，后面的定语从句修饰它。",
  },
  {
    id: "relative-clause",
    start: 8,
    end: 25,
    role: "clause",
    fontLevel: 2,
    underlineStyle: "solid",
    backgroundStyle: "none",
    relation: "modifies",
    targetId: "subject-main",
    isContainer: true,
    labelZh: "定语从句容器",
    explanationZh: "who won the prize 是定语从句，修饰先行词 boy。容器本身只表示范围，内部成分仍按各自角色上色。",
  },
  {
    id: "relative-subject",
    start: 8,
    end: 11,
    role: "subject",
    fontLevel: 2,
    underlineStyle: "none",
    backgroundStyle: "none",
    relation: "belongsToClause",
    targetId: "relative-clause",
    parentId: "relative-clause",
    labelZh: "从句主语",
    explanationZh: "who 在定语从句中作主语。",
  },
  {
    id: "relative-predicate",
    start: 12,
    end: 15,
    role: "predicate",
    fontLevel: 2,
    underlineStyle: "none",
    backgroundStyle: "none",
    relation: "belongsToClause",
    targetId: "relative-clause",
    parentId: "relative-clause",
    labelZh: "从句谓语",
    explanationZh: "won 是定语从句中的谓语动词。",
  },
  {
    id: "relative-object",
    start: 16,
    end: 25,
    role: "directObject",
    fontLevel: 2,
    underlineStyle: "none",
    backgroundStyle: "none",
    relation: "belongsToClause",
    targetId: "relative-clause",
    parentId: "relative-clause",
    labelZh: "从句直接宾语",
    explanationZh: "the prize 作 won 的宾语。",
  },
  {
    id: "main-linking",
    start: 26,
    end: 39,
    role: "linkingPredicate",
    fontLevel: 1,
    underlineStyle: "none",
    backgroundStyle: "none",
    labelZh: "主句系表结构",
    explanationZh: "is my brother 整体作为系表结构，说明主语 The boy 的身份。",
  },
  {
    id: "my-brother-target",
    start: 29,
    end: 39,
    role: "linkingPredicate",
    fontLevel: 1,
    underlineStyle: "none",
    backgroundStyle: "none",
    parentId: "main-linking",
    labelZh: "系表结构核心说明",
    explanationZh: "my brother 是系表结构中的身份说明，保持浅蓝色，不单独标为补足语。",
  },
  {
    id: "appositive-brother",
    start: 41,
    end: 56,
    role: "appositive",
    fontLevel: 1,
    underlineStyle: "doubleWavy",
    backgroundStyle: "none",
    relation: "appositiveOf",
    targetId: "my-brother-target",
    labelZh: "同位语",
    explanationZh: "a quiet student 是 my brother 的同位语，整体对 my brother 作进一步说明；其中 quiet 是修饰 student 的定语。",
  },
  {
    id: "attribute-quiet",
    start: 43,
    end: 48,
    role: "attribute",
    fontLevel: 1,
    underlineStyle: "dotted",
    backgroundStyle: "none",
    relation: "modifies",
    targetId: "appositive-head",
    parentId: "appositive-brother",
    labelZh: "前置定语",
    explanationZh: "quiet 修饰 student。",
  },
  {
    id: "appositive-head",
    start: 49,
    end: 56,
    role: "appositive",
    fontLevel: 1,
    underlineStyle: "none",
    backgroundStyle: "meaningCenter",
    relation: "appositiveOf",
    targetId: "my-brother-target",
    parentId: "appositive-brother",
    labelZh: "同位语中心词",
    explanationZh: "student 是同位语 a quiet student 的中心词。",
  },
  {
    id: "nonfinite-group",
    start: 57,
    end: 78,
    role: "attribute",
    fontLevel: 2,
    underlineStyle: "wavy",
    backgroundStyle: "nonfinite",
    relation: "modifies",
    targetId: "appositive-head",
    groupId: "nonfinite-group-1",
    isContainer: true,
    labelZh: "非限定动词短语作后置定语",
    explanationZh: "reading by the window 整体作后置定语，修饰 student。",
  },
  {
    id: "nonfinite-reading",
    start: 57,
    end: 64,
    role: "nonfinite",
    fontLevel: 2,
    underlineStyle: "none",
    backgroundStyle: "nonfinite",
    relation: "modifies",
    targetId: "appositive-head",
    parentId: "nonfinite-group",
    groupId: "nonfinite-group-1",
    labelZh: "非限定动词本身",
    explanationZh: "reading 是非限定动词本身，颜色按非限定动词规则显示为蓝色。",
  },
  {
    id: "nonfinite-adverbial",
    start: 65,
    end: 78,
    role: "adverbial",
    fontLevel: 2,
    underlineStyle: "dashDotDot",
    backgroundStyle: "none",
    relation: "modifies",
    targetId: "nonfinite-reading",
    parentId: "nonfinite-group",
    groupId: "nonfinite-group-1",
    labelZh: "非限定短语内部状语",
    explanationZh: "by the window 表示 reading 发生的位置。",
  },
];
